name: Enhanced Windows RDP Environment

on:
  workflow_dispatch:

jobs:
  setup-windows:
    name: Setup Windows RDP
    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
      - name: Check System Specs
        run: |
          echo Checking system specs...
          systeminfo | findstr /C:"Total Physical Memory"
          systeminfo | findstr /C:"Available Physical Memory"
          echo CPU Information:
          wmic cpu get name

      - name: Install Ngrok
        run: |
          echo Downloading and setting up ngrok...
          Invoke-WebRequest -Uri "https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip" -OutFile "ngrok.zip"
          Expand-Archive -Path ngrok.zip -DestinationPath .  # استخدم Expand-Archive بدلاً من tar لاستخراج ملف ZIP
          ./ngrok authtoken 2V4ZVr5efWMydD5SRyvxg48Q73t_25NK2LtPxxtDFsMxQzjv6

      - name: Enable RDP and Configure Firewall
        run: |
          echo Enabling Remote Desktop Protocol...
          reg add "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Terminal Server" /v fDenyTSConnections /t REG_DWORD /d 0 /f
          echo Allowing RDP through Windows Firewall...
          netsh advfirewall firewall set rule group="remote desktop" new enable=yes
          echo Remote Desktop Protocol enabled successfully.

      - name: Start Ngrok for RDP
        run: |
          echo Starting ngrok tunnel for RDP...
          ./ngrok tcp 3389 > ngrok.log &

      - name: Show Ngrok Public URL
        run: |
          echo Your RDP public address:
          type ngrok.log | findstr "tcp://"

      - name: Long Running Process (Keep Alive)
        run: |
          echo Running keep-alive loop...
          for /l %x in (0, 1, 999999) do (echo Keep alive... & timeout /t 300)
